[roll] Roll fuchsia [proc][magma] Remove --size_t-is-usize
Needed because of bindgen update to fix:

error: unexpected argument '--size_t-is-usize' found

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/813826
Original-Revision: 484389d9715b5af59e1eab35b636ae9582a23f34
GitOrigin-RevId: fa0646fde50daa8c6f06d389571908f171b97f99
Change-Id: Id5dcd622add6ff2b43b9945d5228f27be8d28f76