[roll] Roll fuchsia [build] Add GN label to golden file error.
Helps developers fix up failures when they happen in CQ first.

Example of the new message format:

```
Error: Golden file mismatch
Please acknowledge this change by updating the golden.

You can run this command:
  cp ... ...
Or you can rebuild with `bless_goldens=true` in your GN args and
`//tools/cmx2cml/tests/goldens:button_checker_unittest` in your build graph.
```

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/699252
Original-Revision: 26d3366d65997b1f274f4811881f4ee29f99fcd5
GitOrigin-RevId: 951c28a970a2ef28d8f4f519f0dcc6468210a4b2
Change-Id: If127086d28f64a148e77d05d0880b5c52a14a6b9