[roll] Roll fuchsia [memory][scripts] Replace cgi with html
The treemap script currently fails with the error:
AttributeError: module 'cgi' has no attribute 'escape'

It also displays a warning message:
DeprecationWarning: 'cgi' is deprecated and slated for removal

The cgi module is only being used to do some string escaping. The html module contains an escape function that we can use. This change replaces
the cgi module with the html module in the treemap.py script.

Tests: manually ran the command from
https://fuchsia.dev/fuchsia-src/development/kernel/memory/memory?visualize_memory_usage#visualize_memory_usage

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/983478
Original-Revision: cc5dc4ccc57b0a501902ac2644dbc73e0f116417
GitOrigin-RevId: cf663ca279a1d926f0a991c29db2ac3736d9e8ef
Change-Id: I45c1df53d700676de4c70d4bdd1d33b0e9303f06