[roll] Roll fuchsia Reland "[fidl] FIDL api summarization tool - initial commit"
This reverts commit 631f8518e42e19809c416e8f7ec1bf3485fd6d88.

Reason for revert: Fixed the test flakiness.  The BUILD.gn needed
a host_test_data declaration to ensure that `fidlc` is available
at test runtime.

Original change's description:
> Revert "[fidl] FIDL api summarization tool - initial commit"
>
> This reverts commit 5afbbd673ac94168034b68304800dff16d5ea8cf.
>
> Reason for revert: Flakiness when trying to find fidlc.
>
> === RUN   TestSummarize
> === RUN   TestSummarize/library_only
>     endtoendtest.go:69: fidlc stdout:
>     endtoendtest.go:70: fidlc stderr:
>     endtoendtest.go:71: fork/exec host_x64/fidlc: no such file or directory
> --- FAIL: TestSummarize (0.00s)
>     --- FAIL: TestSummarize/library_only (0.00s)
> FAIL
>
> Original change's description:
> > [fidl] FIDL api summarization tool - initial commit
> >
> > This change checks in the first code of a FIDL API summarization tool.
> > The goal of the tool is to convert a FIDL intermediate representation
> > into a mainly human-readable list of API elements exposed by the FIDL
> > API.
> >
> > Please see `README.md` for more details.
> >
> > Current status:
> >
> > - Completed a TDD test fixture for processing known examples of API
> >   summarization.
> > - Builds a data model for the API summary, which is simpler than the
> >   FIDL IR, as we anticipate to produce a machine-readable form as well.
> >
> > Original-Bug: 67873
> > Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/467454
>
> TBR=pascallouis@google.com,fmil@google.com,mkember@google.com
>
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Original-Bug: 67873
> Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/475802

TBR=pascallouis@google.com,fmil@google.com,mkember@google.com

Multiply: summary_test
Original-Bug: 67873
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/475858
Original-Revision: 4743131d5e841986083aa0d8aeaffb37d612d928
GitOrigin-RevId: 3d804959d6d0e930139e5d58106e33f140be31a1
Change-Id: I0cd1461ae5aec395afc4ebfd896c68c065c113a4