[roll] Roll fuchsia [superproject] Roll third_party/pigweed pw_cli: Fix logging msec format
Python 3.8 and lower does not check if default_msec_format is set.
Fixes these Logging errors:

```
TypeError: not all arguments converted during string formatting
```

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/130472
Original-Revision: 6ed549f33032e7458629417ae68bf201930b1490
GitOrigin-RevId: 50728092f3ad87b2f84afdfb4d5d60bbbffbd33a
Roller-URL: https://ci.chromium.org/b/8788344678750179057
CQ-Do-Not-Cancel-Tryjobs: true
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/809108
Original-Revision: 85fd36f6fbda454867a6db84afc8e498ff097738
Change-Id: I26f4cc73493da47b0e0a3e03e3c3a0dee122dc40