[roll] Roll fuchsia [wlan][policy] Report correct line number on SME test helpers
Reports the line number of the caller when assertions fail in the SME
stream test helper.

i.e. show this:

```
thread 'main' panicked at 'unexpected variant: Pending',
../../src/connectivity/wlan/wlancfg/src/client/scan.rs:1876:9`
```

instead of this:

```
thread 'main' panicked at 'unexpected variant: Pending',
../../src/connectivity/wlan/wlancfg/src/util/testing/sme_stream.rs:30:9

```

Supersedes fxrev.dev/468977

Test: fx test wlancfg-tests
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/469880
Original-Revision: a0707241870121cc1a357604eb9a157e28b8c643
GitOrigin-RevId: afbb6cc96038810b3db1d9d121b339af07029759
Change-Id: Ib4fac8803ca0aca12e55ff3d88a00433df2764ce