[roll] Roll fuchsia [build] Suppress -Wunused-but-set-variable in grpc
This patch suppresses -Wunused-but-set-variable warning in
grpc third party code that does not comply with.

The code that causes the issue is as the following:
error: variable 'num_transient_failures' set but not used

Original-Bug: 96410
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/664068
Original-Revision: 2f67f7f9b1987ec0a0296995a9ddf61433a3c8f9
GitOrigin-RevId: 3b58cb8074a3ddd6f2569dfea3862dd23dc1d826
Change-Id: I6c707a08b5ad6d354266b5f9316cfa465e909f27