[roll] Roll fuchsia [sysmgr] Remove invalid FIDL call
This was missed in commit 4b50ae56b33124d066bfdff8ff750308e705cd28; the
result is that this log line appears on every boot:

ERROR: [../../sdk/lib/fidl/cpp/internal/proxy_controller.cc(61)] fidl validating error: message is missing a non-nullable handle. message: fuchsia.sys/EnvironmentGetDirectoryRequest, 24 bytes, 0 handles

This removes this invalid call.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/821149
Original-Revision: 0c0aadc2633b71c311ac2a2e437cddab3629fa87
GitOrigin-RevId: 897267704986177dc553ba8a1835d880f7924bc3
Change-Id: I04affa668afcff2b21f5855b9a630b3087be63b1