[roll] Roll llvm-project/libc Revert D137868 "[libc] Fix builtin definition for memory functions"
This reverts commit da5d00ad0cf4d45e38287280c670b08e84e27411.

This caused -Wmacro-redefined
```
.../libc/src/string/memory_utils/op_x86.h:31:9: error: '_mm512_cmpneq_epi8_mask' macro redefined [-Werror,-Wmacro-redefined]
        ^
.../lib/clang/google3-trunk/include/avx512bwintrin.h:294:9: note: previous definition is here
        ^
```

GitOrigin-RevId: ce9df5d5246d7d0fb57d0737f0fc05ae319aaa9e
Original-Revision: e71ff2bc22286e5e9111a925a5a8d0f83b63f7e2
Change-Id: Ib86562e6afc2ce8e48fc672e5fb030b53833635e