[roll] Roll experiences [Ermine] Wrapped the state change in action
Fixed the issue that all launching apps throw the following error:

ERROR: 'package:mobx/src/core/context.dart': Failed assertion: line 220 pos 18: '_state.isWithinBatch': Side effects like changing state are not allowed at this point. Please wrap the code in an "action". Tried to modify: Observable@9

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/experiences/+/573121
Original-Revision: f4cbbc703fbd11932e685656c7e9063dfb671a15
GitOrigin-RevId: 4f9ebeb81e9dda577b3fdc82fa883df7d10e3eb8
Change-Id: I0ecae348fd8683e6f96f253937e58629468c70b2