[roll] Roll fuchsia [fidlgen] Solidify assert(Not)Equal helpers
By advertising `interface{}` for values, one expects a deep comparison
rather than simply a pointer equality as was done previously. This was
fine given the use with primitives, but new uses (e.g.
I58f17d8e901942e3f1d5e297c576ab77b60d609b) are planned.

Checked by changing a test

```
-       assertEqual(t, int(Colors.Green), 2)
+       assertEqual(t, int(Colors.Green), 5)
```

yielding output

```
=== RUN   TestExample
    enum_test.go:15:
        left=2
        right=5
        diff=  int(
        -       2,
        +       5,
          )

--- FAIL: TestExample (0.00s)
```
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/501982
Original-Revision: 3059037c10954e1c61693f118b4a48a8c8c07cad
GitOrigin-RevId: b0b533c84d263d939040e1c65dde34746e3683d7
Change-Id: I2a15a9e42439b39e2c143ac0bcfdb41ba9ec93dd