[roll] Roll fuchsia [wlan][lib] Remove use of private syn export
The `export` module of `syn` was not intended for public use. In the
latest version of `syn`, that module is entirely removed:
https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7

Various other projects encountered breakages due to usage of (now-
removed) `syn::export` module:
- https://github.com/nushell/nushell/issues/2867
- https://github.com/frondeus/test-case/issues/60

The current code (before this CL) will break on the next roll of
our Rust dependencies.

I noticed the compilation issue when attempting to compile with the
latest version of packages:
```
error[E0432]: unresolved import `proc_macro2::ToTokens`
 --> fuchsia/src/connectivity/wlan/lib/bitfield/src/parse.rs:6:19
  |
6 |     proc_macro2::{ToTokens, TokenStream},
  |                   ^^^^^^^^ no `ToTokens` in the root
```

Test: fx test wlan-bitfield-tests
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/469957
Original-Revision: 9aa8b254f0c949e2f0cabb52d6fee849829d9cee
GitOrigin-RevId: de4b97528f70d1d40e41bf4b31616b0b22e94684
Change-Id: I6bdcbb2fd46f427893a0f940f7541df9362d3c80