[roll] Roll third_party/spirv-tools [build] Suppress -Wunused-but-set-var in spirv-tools
This patch suppresses -Wunused-but-set-variable warning in
spirv-tools third party code that does not comply with.

The code that causes the issue is as the following:
../../third_party/spirv-tools/source/util/ilist.h:341:7: error: variable
'sentinel_count' set but not used [-Werror,-Wunused-but-set-variable]

Original-Bug: 96410
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/third_party/spirv-tools/+/662983
Original-Revision: bd9190a3deeb0593c0baa9d869bcdc350c3c85eb
GitOrigin-RevId: 4c1331ef4c4c775a0aa801a9fd9bd71e792ba312
Change-Id: I79426516a09a46e8da666e68b8235e88f52f7f6f