[roll] Roll fuchsia [resultdb] Try to capture 3 lines from stderr as failure_reason
We noticed that capturing a single line from stderr produces very
generic error message: "thread 'main' panicked at 'assertion failed: `(left == right)`"

Tweak the algorithm to capture 3 lines from stderr that hopefully would
show the full error message.

Note that we originally decided to only capture a single line in
https://fxrev.dev/621322 due to concern that we may have stderr from
multiple test cases printed out of order. So this is still less
desirable compared to switching to using `ffx test`.

Examples:
no-ffx - https://ci.chromium.org/ui/p/fuchsia/builders/try/core.x64-release/b8814399138844346545/test-results
ffx - https://ci.chromium.org/ui/p/fuchsia/builders/try/core.x64-release-ffx/b8814399138844346561/test-results

Original-Bug: 99976
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/677893
Original-Revision: a1fdc43eba453bbddfa886cd6106f0bb55216102
GitOrigin-RevId: c912663d3bb567c64e593d2392d5e22d5d718b8a
Change-Id: I2b7d4ad789c8e5dcc82aa16b6e4e085ebb0ad618