[roll] Roll fuchsia [ffx] forward all stdio from daemon to log
The daemon no longer logs to file unless spawned off by ffx itself.

If a user invokes ffx daemon start directly, all IO will reach the
terminal. When the daemon is spawned by the ffx frontend, the
frontend redirects all stdout and stderr to the daemon log file, such
that non-log output is also redirected to that file, including crash
diagnostic output. RUST_BACKTRACE=full is also set in that
environment, so that background crashes are easy to report and
diagnose.

ffx frontend now always has a TermLogger configured, even if logging
is disabled, enabling errors to be output to the terminal.

Test: e2e to be included in self-test later in CL chain, for now
perform an ffx daemon crash invocation, and observe the backtrace in
ffx.daemon.log such as:
     ffx_daemon::daemon: daemon received request: Crash
     thread 'main' panicked at 'instructed to crash by client!'

Original-Bug: 59056

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/421739
Original-Revision: 4cdd0560032ccf6c04faba3ff1ecb192061c1c4c
GitOrigin-RevId: cb4c03d6b847ef2c7b8215d55d3cebfdbdbe9c79
Change-Id: I09e8fb2b5670ba5033cb953eb71e40c16708f050