[roll] Roll fuchsia [build][sdk] Implement optional manifest elements
This allows soft transitions when SDK elements are transitively included in
out-of-repo manifests. When used on https://fxrev.dev/696652 this produces:

  FAILED: sdk/api/core
  ../../build/rbe/output-scanner.sh --label //sdk:core_verify_api\(//build/toolchain/fuchsia:x64\) sdk/api/core -- ../../prebuilt/third_party/python3/linux-x64/bin/python3.8 -S ../../build/sdk/verify_sdk_api.py --manifest gen/sdk/core_molecule.sdk --updated sdk/api/core --reference ../../sdk/manifests/core.manifest
  Elements added to SDK:
   - sdk://fidl/fuchsia.unknown
  Error: SDK contents have changed!
  Please acknowledge this change by running:
    cp /usr/local/google/home/tamird/src/fuchsia/out/qemu-x64/sdk/api/core /usr/local/google/home/tamird/src/fuchsia/sdk/manifests/core.manifest
  Elements can be marked optional with a leading question mark.
  Please remember to complete transitions by marking elements required!

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/707930
Original-Revision: 3192f29cc7c79c2a60866f061452ffa25e81702d
GitOrigin-RevId: 39280fec490c642632733b7b2109dc319a0ddf51
Change-Id: Ibcc2989d87ffa01caab78f41e0c66bfe6e54db67