[roll] Roll fuchsia [cmc] Make output required
`cmc compile` will panic if output is not provided, so make
the field mandatory.

See the new output:

$ ./out/default/host-tools/cmc compile examples/tests/rust/meta/temp_user.cml
error: The following required arguments were not provided:
    --output <output>

USAGE: cmc compile <FILE> --includepath <includepath>... --includeroot <includeroot> --output <output>

Original-Fixed: b/297312018
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/999914
Original-Revision: 62aa2ced2e67789859853c7aceb452d1d6103be7
GitOrigin-RevId: 4adf2ba87dd5bb322ae7918569edc4f183e1600f
Change-Id: Ie34001ea304594e9079718d7dba576717ecca39f