[roll] Roll fuchsia Revert "[starnix] Use VmexResource to make executable memory"
This reverts commit f07617408e643258cdd47b1b34b63b18c6f1a624.

Reason for revert:  CI failing with

[108216/183269] RUST starnix_runner exe.unstripped/starnix_runner
FAILED: starnix_runner exe.unstripped/starnix_runner
mkdir -p ./exe.unstripped &&  RUST_BACKTRACE=1 ../../prebuilt/third_party/rust/linux-x64/bin/rustc --color=always --crate-name starnix_runner ../../src/proc/bin/starnix/main.rs --crate-type bin --e…
error: variable does not need to be mutable
  --> ../../src/proc/bin/starnix/fs/fidl_file.rs:25:13
   |
25 |         let mut service = fkernel::VmexResourceSynchronousProxy::new(client_end);
   |             ----^^^^^^^
   |             |
   |             help: remove this `mut`
   |
   = note: `-D unused-mut` implied by `-D warnings`

error: aborting due to previous error

Original change's description:
> [starnix] Use VmexResource to make executable memory
>
> Previously, we needed to disable the security check in the kernel.
>
> Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/519408

TBR=abarth@google.com,zarvox@google.com,tbodt@google.com

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/519660
Original-Revision: c83c74ce1ddf2f5f344603def303d8e85a4e9724
GitOrigin-RevId: 225533ae4654812bea2a75d016b822262d24a992
Change-Id: Idb641d95b841eb89082d9de67fd2b33b4ca9cb89