[roll] Roll fuchsia [build] Suppress -Wunused-but-set-variable in zstd
This patch suppresses -Wunused-but-set-variable warning in
zstd third party code that does not comply with.

The code that causes the issues is as the following:
third_party/zstd/src/lib/compress/zstd_compress_superblock.c:412:12:
error: variable 'litLengthSum' set but not used

Original-Bug: 77973
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550732
Original-Revision: 3473b255bf7fa27c2fd9a84089fd8a51bba0a95d
GitOrigin-RevId: 75d5be8b8b880fc1f45786e4b92d20c46b0a57d7
Change-Id: Ifeee9b4c8e08078e62df305f25786c24631b892d