[roll] Roll fuchsia [memory] fix overflow panic in `ffx profile memory components` output
The way the kernel accounts and reports statistics changed in
https://fxrev.dev/1059692 . Due to this change, the calculation of
removing zram from reported "Other" is no longer correct, resulting in a
negative value, triggering overflow panic.

```
thread 'main' panicked at ../../src/developer/ffx/plugins/profile/memory/components/src/output.rs:351:55:
attempt to subtract with overflow
```

This patch fixes this by removing the subtraction: we're now
printing the kernel stats as we receive them, fixing the crash and
simplifying the logic.

Original-Bug: 377258904
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1150254
Original-Revision: 517526d98a3652cc401360125571e8410af78bbc
GitOrigin-RevId: c73790147142b8d9d9ff055399cefbf5e32552ba
Change-Id: I8395abc33a80ed240e6d1663feaf6d7438f18c6a