[roll] Roll third_party/openweave-core [build] Suppress -Wunused-but-set-variable in openweave-core
This patch suppresses -Wunused-but-set-variable warning in
openweave-core third party code that does not comply with.

The code that causes the issues is as the following:
third_party/openweave-core/src/lib/support/SerialNumberUtils.cpp:216:14:
error: variable 'mfgYear' set but not used

Original-Bug: 77973
Original-Revision: 14f76e27123473bdeec54512a733df02e737fd6c
GitOrigin-RevId: 6320bd0cbdae4553db604614e9d6c7a8770841f3
Change-Id: I660fe421d5ad160e8d5fb35c7f1f54be4dfca4ce