[roll] Roll fuchsia [intl] Tightens the string naming controls
In an early field test, lucasradaelli@ discovered that `strings_to_fidl`
let an identifier name such as "role_table," go through. Notice the
extra unwanted comma at the end.

While `strings_to_fidl` doesn't really have a preference, the FIDL file
that is generated based on strings.xml ends up with unallowed syntax.

So, we tighten the behavior to fail fast instead of generating a FIDL
file that won't pass a followup FIDL compilation step.

Example error given below:

```
╰─>$ ./strings_to_fidl --input=$HOME/strings.xml --output=$HOME/strings.xml.out ; cat $HOME/strings.xml.out
Error: while parsing dictionary

Caused by:
    0: in state: String { name: "string_name,", text: "text_string" }
    1: name is not acceptable: 'string_name,', does not match: ^[_a-zA-Z][_a-zA-Z_0-9]*$
```

Original-Bug: 50720
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/385229
GitOrigin-RevId: 7ce4cbaf5565a6ea792cedcb59f4ceac8287b4fa
Change-Id: Ica0d97d480cab271bd9f96e98fed3dd575a4471c