[roll] Roll fuchsia Revert "[alln] remove -O2"
This reverts commit 99b75615feb0431b7bd772555bf4e72afae85794.

Reason for revert: suspected candidate for the consistent host_x64/fs-test failures in GI

Original change's description:
> [alln] remove -O2
>
> Warning   aux         size change for test/core-handle-wait: -6% (64.0K)
> Warning   aux         size change for test/mt8167-audio-lib-test: -7%
> (60.0K)
> Error     aux         size change for test/core-c11-condvar: +8% (52.0K)
> Error     aux         size change for lib/libfs-management.so: +4%
> (93.4K)
> Warning   aux         size change for test/core-vmar: +1% (492.2K)
> Warning   aux         size change for test/range: +1% (320.0K)
> Warning   aux         size change for bin/minfs: +1% (472.3K)
> Warning   aux         size change for test/minfs-unit: +1% (1.3M)
> Error     aux         size change for bin/sh: +2% (180.4K)
> Error     aux         size change for lib/libtrace-engine.so: +9%
> (45.6K)
> Error     aux         size change for bin/display-test: +2% (160.0K)
> Error     aux         size change for test/fs: +3% (958.9K)
> Error     aux         size change for
> test/metrics-composite-latency-event: +8% (104.0K)
> Warning   aux         size change for test/minfs-integration: +1%
> (688.0K)
> Warning   aux         size change for test/block-watcher-test: +0%
> (860.0K)
> Error     aux         size change for
> test/blobfs-large-integration-use-second-bitmap-test: +3% (124.0K)
> Warning   aux         size change for test/futex-ownership: -2% (208.0K)
> Warning   aux         size change for test/journal-unit: +0% (856.0K)
> Error     aux         size change for test/core-object-wait: +5% (76.0K)
> Error     aux         size change for test/libzbi-test: +9% (92.0K)
> Error     aux         size change for test/metrics-inspect: +7% (112.0K)
> Error     aux         size change for
> test/blobfs-large-integration-max-reservation-test: +3% (120.0K)
> Warning   aux         size change for lib/libfdio.so: +1% (302.1K)
> Warning   aux         size change for test/blobfs-unit: +1% (2.2M)
> Error     aux         size change for test/disk-inspector-unit-test: +4%
> (272.0K)
> Warning   aux         size change for test/usb-request-test: +0%
> (424.0K)
> Warning   aux         size change for test/core-vmo: +1% (872.0K)
> Error     aux         size change for test/fshost-inspect-test: +3%
> (244.0K)
> Error     aux         size change for test/storage-metrics: +3% (124.0K)
> Warning   aux         size change for test/mock-function-test: -8%
> (52.0K)
> Warning   aux         size change for test/ptysvc-test: +0% (472.0K)
> Warning   aux         size change for bin/blobfs: +1% (1.4M)
> Warning   aux         size change for test/pci-driver-test: -8% (48.0K)
> Warning   aux         size change for test/fshost-test: +0% (472.0K)
> Error     aux         size change for test/core-sync-completion: +5%
> (76.0K)
> Error     aux         size change for test/mt8167s_ref-test: +5% (76.5K)
> Error     aux         size change for test/uart-unittests: +4% (84.0K)
> Error     aux         size change for bin/netsvc: +2% (177.1K)
> Error     aux         size change for test/core-futex: +3% (108.0K)
> Error     aux         size change for test/x86-cros-ec-test: +4%
> (100.3K)
> Warning   aux         size change for test/core-socket: +1% (252.0K)
> Warning   aux         size change for test/blobfs-integration-test: +1%
> (1.8M)
> Error     aux         size change for test/ftl-lib-test: +2% (180.0K)
> Warning   aux         size change for test/optee-message-test: +1%
> (244.0K)
> Warning   aux         size change for test/runtests-utils: +0% (416.5K)
> Error     aux         size change for test/audio-test: +7% (60.0K)
> Error     aux         size change for test/metrics-cobalt: +3% (104.0K)
> Error     aux         size change for test/x86-board: +4% (84.0K)
> Warning   aux         size change for bin/mkfs-msdosfs: -2% (20.3K)
> Error     aux         size change for test/inspect: +6% (708.0K)
> Error     aux         size change for test/fs-recovery: +5% (72.0K)
> Error     aux         shared library removed from test/fit:
> libc++abi.so.1
> Error     image       size change for driver/asix-88179.so: +6% (61.6K)
> Error     image       size change for bin/sh: +2% (180.4K)
> Error     image       size change for driver/fragment.proxy.so: +7%
> (57.7K)
> Warning   image       size change for bin/sdio: -1% (44.9K)
> Warning   image       size change for bin/lspwr: -1% (20.4K)
> Warning   image       size change for lib/libfdio.so: +1% (302.1K)
> Error     image       size change for bin/gpt: +7% (56.0K)
> Error     image       size change for driver/e1000.so: +2% (281.8K)
> Error     image       size change for lib/libblktest.so: +10% (81.5K)
> Error     image       size change for bin/disk-inspect: +6% (200.4K)
> Warning   image       size change for driver/display.so: +1% (349.7K)
> Warning   image       size change for bin/blobfs: +1% (1.4M)
> Warning   image       size change for bin/svchost: +1% (228.0K)
> Warning   image       size change for bin/mkfs-msdosfs: -2% (20.3K)
> Warning   image       size change for driver/mtk-thermal.so: -8% (49.5K)
> Warning   image       size change for bin/runtests: +1% (248.0K)
> Error     image       size change for test/audio-test: +7% (60.0K)
> Error     image       size change for bin/hid: +6% (64.0K)
> Warning   image       size change for driver/optee.so: +1% (213.5K)
> Warning   image       size change for driver/sysmem.so: +1% (361.8K)
> Error     image       size change for driver/usb-peripheral-test.so:
> +13% (33.6K)
> Warning   image       size change for bin/minfs: +1% (472.3K)
> Error     image       size change for lib/libtrace-engine.so: +9%
> (45.6K)
> Error     image       size change for bin/ihda: +6% (64.0K)
> Warning   image       size change for test/usb-device: +1% (264.1K)
> Error     image       size change for driver/i2c-hid.so: +8% (49.8K)
> Error     image       size change for driver/dwc2.so: +8% (53.5K)
> Error     image       size change for driver/amlogic-display.so: +3%
> (133.6K)
> Error     image       size change for bin/mutex_pi_exerciser: +5%
> (80.0K)
> Error     image       size change for driver/ftl.so: +2% (145.7K)
> Warning   image       size change for driver/goldfish-display.so: +1%
> (237.7K)
> Error     image       size change for driver/sdmmc.so: +2% (161.7K)
> Error     image       size change for driver/mt8167s-display.so: +4%
> (101.6K)
> Error     image       size change for driver/virtio_socket.so: +3%
> (105.6K)
> Error     image       size change for lib/libfs-management.so: +4%
> (93.4K)
> Error     image       size change for bin/trace-benchmark: +11% (76.0K)
> Error     image       size change for
> driver/usb-two-endpoint-hid-fake-usb.so: +15% (29.6K)
> Error     image       size change for driver/intel-rtc.so: +13% (33.8K)
> Error     image       size change for driver/gpt.so: +13% (33.6K)
> Error     image       size change for driver/ams-light.so: +18% (25.5K)
> Error     image       size change for driver/zxcrypt.so: +5% (81.6K)
> Error     image       size change for driver/fake-usb-cdc-acm.so: +15%
> (29.6K)
> Error     image       size change for driver/mtk-sdmmc.so: +10% (41.5K)
> Error     image       size change for driver/hid.so: +3% (117.8K)
> Error     image       size change for driver/fidl-llcpp-driver.so: +11%
> (37.5K)
> Error     image       size change for driver/mtk-clk.so: +11% (37.5K)
> Error     image       size change for driver/ftdi.so: +6% (65.5K)
> Warning   image       size change for bin/miscsvc: +1% (532.0K)
> Error     image       size change for bin/usbctl: +7% (56.0K)
> Error     image       size change for driver/usb-virtual-bus.so: +6%
> (65.5K)
> Error     image       size change for driver/dwc3.so: +8% (49.9K)
> Error     image       size change for driver/mt-musb-peripheral.so: +9%
> (45.5K)
> Error     image       size change for driver/focaltech.so: +9% (45.7K)
> Error     image       size change for driver/ftdi-fake-usb.so: +15%
> (29.5K)
> Error     image       size change for driver/aml-thermal-s905d2g.so: +5%
> (73.5K)
> Error     image       size change for bin/netsvc: +2% (177.1K)
> Error     image       size change for driver/intel-i915.so: +6% (185.7K)
> Warning   image       size change for bin/fshost: +1% (688.0K)
> Error     image       size change for driver/aml-i2c.so: +9% (45.9K)
> Warning   tests       size change for test/core-handle-wait: -6% (64.0K)
> Warning   tests       size change for test/mt8167-audio-lib-test: -7%
> (60.0K)
> Error     tests       size change for test/core-c11-condvar: +8% (52.0K)
> Error     tests       size change for lib/libfs-management.so: +4%
> (93.4K)
> Warning   tests       size change for test/core-vmar: +1% (492.2K)
> Warning   tests       size change for test/range: +1% (320.0K)
> Warning   tests       size change for bin/minfs: +1% (472.3K)
> Warning   tests       size change for test/minfs-unit: +1% (1.3M)
> Error     tests       size change for bin/sh: +2% (180.4K)
> Error     tests       size change for lib/libtrace-engine.so: +9%
> (45.6K)
> Error     tests       size change for bin/display-test: +2% (160.0K)
> Error     tests       size change for test/fs: +3% (958.9K)
> Error     tests       size change for
> test/metrics-composite-latency-event: +8% (104.0K)
> Warning   tests       size change for test/minfs-integration: +1%
> (688.0K)
> Warning   tests       size change for test/block-watcher-test: +0%
> (860.0K)
> Error     tests       size change for
> test/blobfs-large-integration-use-second-bitmap-test: +3% (124.0K)
> Warning   tests       size change for test/futex-ownership: -2% (208.0K)
> Warning   tests       size change for test/journal-unit: +0% (856.0K)
> Error     tests       size change for test/core-object-wait: +5% (76.0K)
> Error     tests       size change for test/libzbi-test: +9% (92.0K)
> Error     tests       size change for test/metrics-inspect: +7% (112.0K)
> Error     tests       size change for
> test/blobfs-large-integration-max-reservation-test: +3% (120.0K)
> Warning   tests       size change for lib/libfdio.so: +1% (302.1K)
> Warning   tests       size change for test/blobfs-unit: +1% (2.2M)
> Error     tests       size change for test/disk-inspector-unit-test: +4%
> (272.0K)
> Warning   tests       size change for test/usb-request-test: +0%
> (424.0K)
> Warning   tests       size change for test/core-vmo: +1% (872.0K)
> Error     tests       size change for test/fshost-inspect-test: +3%
> (244.0K)
> Error     tests       size change for test/storage-metrics: +3% (124.0K)
> Warning   tests       size change for test/mock-function-test: -8%
> (52.0K)
> Warning   tests       size change for test/ptysvc-test: +0% (472.0K)
> Warning   tests       size change for bin/blobfs: +1% (1.4M)
> Warning   tests       size change for test/pci-driver-test: -8% (48.0K)
> Warning   tests       size change for test/fshost-test: +0% (472.0K)
> Error     tests       size change for test/core-sync-completion: +5%
> (76.0K)
> Error     tests       size change for test/mt8167s_ref-test: +5% (76.5K)
> Error     tests       size change for test/uart-unittests: +4% (84.0K)
> Error     tests       size change for bin/netsvc: +2% (177.1K)
> Error     tests       size change for test/core-futex: +3% (108.0K)
> Error     tests       size change for test/x86-cros-ec-test: +4%
> (100.3K)
> Warning   tests       size change for test/core-socket: +1% (252.0K)
> Warning   tests       size change for test/blobfs-integration-test: +1%
> (1.8M)
> Error     tests       size change for test/ftl-lib-test: +2% (180.0K)
> Warning   tests       size change for test/optee-message-test: +1%
> (244.0K)
> Warning   tests       size change for test/runtests-utils: +0% (416.5K)
> Error     tests       size change for test/audio-test: +7% (60.0K)
> Error     tests       size change for test/metrics-cobalt: +3% (104.0K)
> Error     tests       size change for test/x86-board: +4% (84.0K)
> Warning   tests       size change for bin/mkfs-msdosfs: -2% (20.3K)
> Error     tests       size change for test/inspect: +6% (708.0K)
> Error     tests       size change for test/fs-recovery: +5% (72.0K)
> Error     tests       shared library removed from test/fit:
> libc++abi.so.1
> Error: summaries do not match!
>
> Bug:52722
>
> Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/400957

TBR=phosek@google.com,pylaligand@google.com,shayba@google.com,rdzhuang@google.com

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Original-Bug: 52722
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/410387
Original-Revision: 2d323540e1cfaf3a99926f13e0b6c3c2efaea5d5
GitOrigin-RevId: 52872657d4f189277c0d6b9e444569112affafc5
Change-Id: Iabdcb9d03e5a836ea0b7e3f0b24b825d6da4024e