[roll] Roll fuchsia [build] Suppress -Wunused-but-set-var in boringssl
This patch suppresses -Wunused-but-set-variable warning in
boringssl third party code that does not comply with.

The code that causes the issue is as the following:
../../third_party/boringssl/src/crypto/x509/t_x509.c:326:18: error:
variable 'l' set but not used

Original-Bug: 96269
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/662282
Original-Revision: 099c845cbe4ca8552acbc6f1858277e75f63cfce
GitOrigin-RevId: e09567aa36d710c1e43382a85119622bcf25cfa0
Change-Id: I9a31192fd13413fccfa7ed9e59ff18b92bca9aa7