[roll] Roll fuchsia [build] Suppress -Wunused-but-set-variable in openbsd-netcat
This patch suppresses -Wunused-but-set-variable warning in
openbsd-netcat third party code that does not comply with.

The code that causes the issues is as the following:
1) ../../src/connectivity/network/tools/nc/third_party/openbsd-netcat/netcat.c:122:25:
error: variable 'socksv' set but not used
2) ../../src/connectivity/network/tools/nc/third_party/openbsd-netcat/netcat.c:129:30:
error: variable 'proxyhost' set but not used
3) ../../src/connectivity/network/tools/nc/third_party/openbsd-netcat/netcat.c:129:47:
error: variable 'proxyport' set but not used

Original-Bug: 77973
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550725
Original-Revision: ea9bf767b0d26c93b28f6ef050ca2fd1a49af5e4
GitOrigin-RevId: 93723219d4cf9060b4970f96f97a1f47c0de05b2
Change-Id: I77bce5fd9c4ca85fc269d23b658d2d3ef401b177