[roll] Roll third_party/ffmpeg [build] Suppress -Wextra-semi in ffmpeg
This patch suppresses -Wextra-semi warning in
ffmpeg third party code that does not comply with.

One of the lines that causes the issue is as the following:
third_party/ffmpeg/libavcodec/pcm.c:583:1: error: extra ';' outside of a
function [-Werror,-Wextra-semi]

Original-Bug: 56257
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/third_party/ffmpeg/+/608049
Original-Revision: 814c2b83c3f43aee6e62b986038e032efe046304
GitOrigin-RevId: f7aaa4a36e01f3efbd15c5c475cfe6db6adda732
Change-Id: I1fcf3f2c801c6b2372f1a00d2aefbaeea62d78df