[roll] Roll fuchsia [escher] Fix uint64_t to uint32_t error
For some reason, this error only appears on the clang canary builders.

error: implicit conversion loses integer precision: 'long' to 'uint32_t' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
      ((latch_time - pose_buffer.base_time) / pose_buffer.time_interval) % pose_buffer.num_entries;
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~

Fix so this will help unblock the next clang roll.

TEST=Tested locally with the new clang revision.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/433522
Original-Revision: 6feb86099ed5d6861ba4f944c949418335d0fc17
GitOrigin-RevId: 5fb5655b4f76a8408c2bbd62b81476f641118c6f
Change-Id: I4e4b45358d1f42ff103818a1d7829a9ea69ac2d5