[roll] Roll fuchsia [perfcompare] Improve error when perfcompare.py is run with no arguments
Before this change, running perfcompare.py with no arguments
unhelpfully raises an exception:

  $ python3 ./src/testing/perfcompare/perfcompare.py
  ...
  AttributeError: 'Namespace' object has no attribute 'func'

The fix is to add required=True so that it prints a usage message
instead:

  $ python3 ./src/testing/perfcompare/perfcompare.py
  usage: perfcompare.py [-h] {compare_perf,run_local,validate_perfcompare} ...
  perfcompare.py: error: the following arguments are required: {compare_perf,run_local,validate_perfcompare}

This problem was introduced by switching to Python 3.  In Python 2,
add_subparsers() didn't take a "required" argument, and argparse would
give a "too few arguments" usage error if a subcommand wasn't given.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/965156
Original-Revision: 310412b94b33a1958b1b8f44134fca7189e01326
GitOrigin-RevId: ef8be2ae80b197e7564ff91b2bceabe3c6890529
Change-Id: I1d3e3e43c5cfd45bb8e1047124c98ca0ebd728b1