[roll] Roll fuchsia [zircon] Add required c++ headers
An upstream change in clang may have moved some libc++ headers, leading
to some missing function names (mostly `error: no member named 'move' in
namespace 'std'`). This includes headers for functions where they are
needed.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/548498
Original-Revision: cbc3dc6b7c119573b05fcbe3f20235eb7570eb6e
GitOrigin-RevId: fafa4a2e93efe34310d41eab7670abe8333d3b85
Change-Id: I3060d734995aefce9a401c9bc6670a3dec67b59b