[roll] Roll fuchsia [build] Suppress -Wunused-but-set-variable in ath10k
This patch suppresses -Wunused-but-set-variable warning in
atheros/ath10k third party code that does not comply with.

The code that causes the issues is as the following:
../../src/connectivity/wlan/drivers/third_party/atheros/ath10k/swap.c:86:12: error: variable 'seg_size' set but not used

Original-Bug: 77973
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550729
Original-Revision: 4689b6d2a98aa4b46e53a7ffb2f5ff23ce48eee0
GitOrigin-RevId: d67fc29fd50a49a48f009c7b346eec6fe3041996
Change-Id: I81cbf0f75a3c7d1b1fdacdff47e9074337588892