[roll] Roll fuchsia [fuchsia-controller] Fix returning Sockets from FIDL methods.
This adds testing to ensure that decoding sockets works as intended.
This also adds some additional debugging code that was not in place
previously.

Without this code we would get an exception for attempting to convert a
u64::INT_MAX into a u32 which would look like the following:

```
OverflowError: Value 18446744073709551615 too large for u32
```

crjohns@ found a quick solution to this issue at fxr/1266793 and this
change adds some testing to prevent regression.

Original-Fixed: 415380059

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1267168
Original-Revision: 3abd4dd35eee5a80203bb82fc8d8d6eccb6a0280
GitOrigin-RevId: 8ae21a4038d0c96910a8b1fe485404787707abe9
Change-Id: Ib64dc436988040430144cd7f66de3f7fafafeb6f