[roll] Roll fuchsia [fint] Parse ninja stderr in addition to stdout
In https://fxrev.dev/508299 I incorrectly assumed that ninja's "ninja:
error: ..." output logs were printed to stdout along with the status
logs like "[1/12345] STAMP ...". However, it turns out that the "ninja:
error: ..." logs are actually printed to stderr, which is why "ninja:
error" failures weren't getting parsed correctly, e.g.:
https://ci.chromium.org/b/8850337454975083648. So we need to update the
ninja output parser to check stderr as well as stdout.

Ideally there would be separate parsers for stdout and stderr, because
each type of log should consistently be printed to either stdout or
stderr, but it's simplest to just use the same parser struct to handle
both stdout and stderr.

Original-Bug: 67861
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/514301
Original-Revision: df861d91da79f7fb3350b583d5cbf304202c3d53
GitOrigin-RevId: 754a1a5ee04c4ff632825eaaa1f702b6931c0a1c
Change-Id: I56782a44dbd345be17774751044c82b4b1abe672