[roll] Roll fuchsia [src/lib/fuchsia] Improve compile error output.
The transformer crate goes through a bunch of effort to avoid
panics and to use errors that can be turned into compiler errors
which preserve spans. But the proc macro entry points were
unwrapping those results instead of passing them back to rustc
as compiler errors.

Replaces

```
error: custom attribute panicked
  --> ...
   |
25 | #[fuchsia::main(logging_tags=["...", threads=2])]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: called `Result::unwrap()` on an `Err` value: Error("expected string literal")
```

with

```
error: expected string literal
  --> ...
   |
25 | #[fuchsia::main(logging_tags=["...", threads=2])]
   |                                      ^^^^^^^
```

And should similarly improve other compiler errors.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1235171
Original-Revision: 8dc96c2ae9cfd2a5c99fdc4f8e11bc02093bb3e4
GitOrigin-RevId: c654ba6621cb4686ccae7e808b5900a735c77f90
Change-Id: I3dfce533e1a8a520c56d13729ad5b0c2a4b4c577