[roll] Roll third_party/pigweed pw_cli: Fix logging msec format
Python 3.8 and lower does not check if default_msec_format is set.
Fixes these Logging errors:

```
TypeError: not all arguments converted during string formatting
```

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/130472
Original-Revision: 6ed549f33032e7458629417ae68bf201930b1490
GitOrigin-RevId: 94e1ad88c9ecc97bcf8308c9459c597455395bfa
Change-Id: Iec3c9e0da3c46eb1fe0318ca08768fa10223237a