[roll] Roll fuchsia [sync-from-stem] More helpful message if fuchsia rev not found
In the window between where the Fuchsia rev lands, and it's rolled
through GI, sync-from-stem will fail to find the appropriate integration
revision (because there isn't one until it's in an integration
manifest). Previously this would result in a stack dump like:

    sync-from-stem: updating in /work/fuchsia/integration
    sync-from-stem: integration now at af5412e642229c4782ae1832ba5389600eb2ab90
    Traceback (most recent call last):
      File "/work/fuchsia/scripts/sync-from-stem.py", line 266, in <module>
        sys.exit(main())
      File "/work/fuchsia/scripts/sync-from-stem.py", line 258, in main
        to_revision(env, fuchsia_rev, f_to_i[fuchsia_rev])
    KeyError: '2b556a202ced24f7e4f797f1eddeae6036653c45'

Instead print a somewhat more informative error:

    sync-from-stem: updating in /work/fuchsia/integration
    sync-from-stem: integration now at 0087f658280f5828edf4e06efa540b6f453c3686
    sync-from-stem: fuchsia rev 2b556a202ced24f7e4f797f1eddeae6036653c45 not found in integration, not rolled yet?

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/405453
Original-Revision: cd2c5b1b1197665450d661fbd793454d11fa4980
GitOrigin-RevId: d30c6e6ad8e9cbbb3c2f01efd6c9785deba0e5a5
Change-Id: I80926f20e2830c20261083ce32267c71c3252d9f