[roll] Roll fuchsia [fidl][rust] Mark QueryResponseFut with T: Unpin
When compiling with the latest futures 0.3.9 (rather than the 0.3.6 we
currently have pinned), I saw the following compilation error:

error[E0277]: `T` cannot be unpinned
on lines 78 and 79 of src/lib/fidl/rust/fidl/src/client.rs:78
(full error message at go/paste/5141922172633088)

The compiler suggested restricting T with `T: Unpin`, which resolved the
compilation error (without causing any new ones). As I understand it,
that means all the types used with QueryResponseFut were already Unpin.

Test: no behavior change expected
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/469997
Original-Revision: 4fdd493eae9e9140da685b497efd674ca8f989c6
GitOrigin-RevId: db0904433860a756c608c562cb1a9acf2574577b
Change-Id: I9e4681a32062e157ddefa8fe7d151c5837ac552b