[roll] Roll fuchsia [superproject] Roll llvm-project/libc [libc] Fix compilation on 32-bit systems
This fixes the following compilation error: no known conversion from 'off_t *'
(aka 'long long *') to 'long' for 5th argument.

Since pointers are 32-bit long anyway, casting it to long shouldn't be a
problem. Tested on rv32.

Reviewed By: sivachandra

Differential Revision: https://reviews.llvm.org/D157792

GitOrigin-RevId: 08675b0721bd86c330d93d5ad84f340bbec0ebd7
Original-Revision: 4cc81ad6c3cf2fc4908b7d99f3cfa2c38b25c685
Roller-URL: https://ci.chromium.org/b/8772596416502063985
CQ-Do-Not-Cancel-Tryjobs: true
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/903038
Original-Revision: 4b6d03d731a6d6d9f0c4ed5e2b0c422ade263009
Change-Id: I8db9c32fed9ad29e408de2d021822db26e2e20ed