[roll] Roll fuchsia Revert "[ffx] Support Overnet over VSOCK"
This reverts commit d4e36c68f96d46b63ea8d24063235a4fa031aa30.

Reason for revert:
error[E0599]: no associated item named `SOCK_NONBLOCK` found for struct `SockFlag` in the current scope
  --> ../../src/developer/ffx/daemon/target/src/overnet/vsock.rs:25:27
   |
25 |     let flags = SockFlag::SOCK_NONBLOCK;
   |                           ^^^^^^^^^^^^^ associated item not found in `SockFlag`

Original change's description:
> [ffx] Support Overnet over VSOCK
>
> Change-Id: I7411be0e1f2a54074bf5c5fd58c1e89516248262
> Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1215428
> Reviewed-by: Steven Grady <slgrady@google.com>
> Commit-Queue: Auto-Submit <auto-submit@fuchsia-infra.iam.gserviceaccount.com>
> Fuchsia-Auto-Submit: Casey Dahlin <sadmac@google.com>

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1239264
Original-Revision: 75119786b8db5ba0ad579ce517343cf3413aa358
GitOrigin-RevId: 3d011a9c62357c9fc9fb82597d2b9f96223b34e4
Change-Id: I72921168c67826c9a7dbcefbea4b5372b7b4c6c8