[roll] Roll fuchsia [audio] Add DAI support sketelon to virtual_audio
Also create a default PostToDispatcher() in VirtualAudioDriver and
a pure virtual dispatcher() used by PostToDispatcher().

Original-Bug: 124865
Test: Switch to open DAI driver and back to a StreamConfig driver.
$ fx shell virtual_audio --dai --add --wait --stream --add --wait
Executing `--dai' command...
Then in another shell:
$ fx shell ls /dev/class/dai
8e73fc7a
And after pressing a key in the first shell
$ fx shell ls /dev/class/audio-output
7a29810f

Test: get-gain reports an error for DAI.
$ fx shell virtual_audio --add --get-gain --dai --add --get-gain
Executing `--add' command...
Executing `--get-gain' command...
--Received Gain   (mute: 0, agc: 0, gain: -0.75000 dB) for output
Executing `--dai' command...
Executing `--add' command...
Executing `--get-gain' command...
ERROR: Get gain failed

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/832081
Original-Revision: 31c3fb13d6064b0ec2f9404ad733cc56222e090d
GitOrigin-RevId: 185d49556414dc93be5b063be3c193ce4968c6dd
Change-Id: Iaee4e3a34a554bb87649a95ee7adae429098364e