[roll] Roll fuchsia [sysmem] Fix missing dependency on llcpp in tests
From:
https://ci.chromium.org/p/fuchsia/builders/try/fuchsia-host-mac-subbuild/b8879206045376978672

FAILED: obj/zircon/system/utest/sysmem/sysmem.sysmem_tests.cc.o
...
../../zircon/system/utest/sysmem/sysmem_tests.cc:8:10: fatal error: 'fuchsia/sysmem/llcpp/fidl.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

I think this often would work if that file's already built, but
depending on ordering, the header might not have been generated.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/392857
Original-Revision: f62e6a2872e4a65b9a0e4d5f0b22da05ca17f5bb
GitOrigin-RevId: e28955d3b9d546aa531aa7abb810f11692da12b3
Change-Id: Ic13632d1ee753634f37c39f33b843d277fec9af7