[roll] Roll fuchsia [fvdl] Improve error message when starting fvdl
When a user tries to run fvdl or ffx emu from the SDK, but they forget
the --sdk flag, the error it prints is:

Error: Cannot read path info from root_dir None

This is not helpful for debugging the reason for the failure, which is
that the user needs to run in the Fuchsia directory and include the
--sdk flag.

This CL changes the error message to be more helpful for the users and
explain how to get past the problem.

Original-Bug: 80407
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/556603
Original-Revision: 78421e3cad56da67d5d1ad5ff3ef23ddfc34775c
GitOrigin-RevId: e198435c4b0a1d5daa76425adc1616c89799d158
Change-Id: I80ffe161d99e78c4cfe4581313abeba0cc505ca3