[roll] Roll fuchsia [fdio/tests] Avoid conversion warning
../../sdk/lib/fdio/tests/fdio_open_max.c:12:13: error: implicit conversion loses integer precision: 'long' to 'int' [-Werror,-Wshorten-64-to-32]
  int max = sysconf(_SC_OPEN_MAX);

Add sdk tests to buildbot, since they are apparently not included.

Restrict fdio host tests to Linux, since they do not build on MacOS.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/431858
Original-Revision: d2e4431c4231f7e14e044c343b7c8d6c64066e5c
GitOrigin-RevId: b79ea5541bfee6aabe5ae8a07238876437130b61
Change-Id: I79cf0180669bcf19d857b96e1d4fc6cca04581d4