[roll] Roll fuchsia [versioning] Define FUCHSIA_HEAD as a decimal number
When I tried using FUCHSIA_HEAD, the compiler errored with

  ../../sdk/lib/fit/include/lib/fit/task_set.h:49:26: error: expected a version of the form 'major[.minor[.subminor]]'
  class ZX_AVAILABLE_SINCE(FUCHSIA_HEAD) task_set {
                           ^
  gen/zircon/public/sysroot/cpp/include/zircon/availability.h:12:22: note: expanded from macro 'FUCHSIA_HEAD'
  #define FUCHSIA_HEAD 0xffffffff

switching to a decimal number fixes it.
Also removes the mention to fxbug.dev/104513 since the linked bug
is closed with the decision to not upstream to clang.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/799685
Original-Revision: 50ce21383a5dd417751d58cc417737f9329837a4
GitOrigin-RevId: 5b222153806c9a34c59dda7e0d3c646f2e1b8700
Change-Id: I65b1070a6e21a1711376ae595f79a85cbc57b65e