[roll] Roll fuchsia [superproject] Roll third_party/pigweed pw_unit_test: Fix -Waddress warning when verifying RUN_ALL_TESTS
When Google Test back-end is used for pw_unit_test GCC reports warning
as follows:

pw_unit_test/public/pw_unit_test/framework.h:181:30: error: the address of 'int RUN_ALL_TESTS()' will never be NULL [-Werror=address]

This happens only with Google Test back-end, because pw_unit_test uses
"#define RUN_ALL_TESTS() ..." and in such case the static_assert is not
used.

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/243133
Original-Revision: a4636bc83d6905cb252a65d19eab4ec2478af42b
GitOrigin-RevId: f4c8e93e87245a4d4c1e82bb9a16514990c42dea
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1142099
Original-Revision: f6456ff926fa54bd0250bd567891aeead1d4ebb9
Change-Id: I7b353093b4de1632483ca4e7b0455607936bc58c