[roll] Roll fuchsia [trace] Properly Terminate in Rust Trace Benchmark
Fully terminate the trace after finishing instead of just stopping.

Previously, tests running after the microbenchmark tests would emit log
messages such as:
```
INFO: [trace_manager.cc(73)] Controller is gone, terminating trace
ERROR: [src/performance/trace_manager/trace_manager.cc(94)] Ignoring initialize request, trace already initialized
ERROR: [src/performance/trace_manager/tracee.cc(404)] #27 {37875:ktrace_provider}: Failed to write provider info record to trace.
ERROR: [src/performance/trace_manager/trace_session.cc(441)] Encountered unrecoverable error writing socket
```
After this change, these no longer occur.

Original-Bug: 135955
Original-Bug: 135953
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/939205
Original-Revision: 1cc078561f775de996924391a501325d9b99753e
GitOrigin-RevId: 5f222796e34bff58374384be9bf0ac3e7347fe2f
Change-Id: Ib2f33178d17ff5099e28a85846662e4670a7a0e9