[roll] Roll third_party/mesa [build] Suppress -Wunused-but-set-variable
This patch suppresses -Wunused-but-set-variable warning
that mesa code does not comply with.
The code that causes the warnings is as the following:
1) third_party/mesa/src/compiler/nir/nir_lower_packing.c:158:9: error: variable 'progress' set but not used
2) third_party/mesa/src/intel/vulkan/anv_descriptor_set.c:1122:27: error: variable 'desc' set but not used

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/third_party/mesa/+/547261
Original-Revision: 70223bec16782d61261c05676475dfad2289ca0f
GitOrigin-RevId: 579ac208abdcb86dbaba3a56d9786704566edf1c
Change-Id: I31e59690910581e9f08fe24e4e114851e4febaae