[roll] Roll fuchsia [bazel_sdk] Misc fix for Bazel SDK test suite.
This fixes a few things that prevent the Bazel SDK test suite
from being invoked directly with `bazel` in the
//build/bazel_sdk/tests directory, as opposed as using
the `bazel_test.py` script. See associated bug for more detail.

- Disable Bzlmod by default, though it is possible to re-enable
  it manually from the command-line, e.g.:

  ```
  bazel test --enable_bzlmod //:tests
  ```

  But note that this use-case is still completely broken for now.

- Upgrade skylib revision in WORKSPACE.bazel as some test rules
  depend on newest features of the library (e.g. `failure_message`
  in `diff_test()`).

- Add an `http_archive()` directive to use a newest `@platforms`
  repository, otherwise analysis fails with labels referencing
  `@platforms//os:visionos` somewhere).

- Fix the compact python toolchain repository rule logic to
  extract the Python version of the system-installed version.
  It turns out that `pip3.XX` is no always installed alongside
  `python3.XX`.

This CL does not fix everything, in particular, `bazel test //:tests`
still fails because no host C++ toolchain is detected, and one is
required to run the symbol-stripping action that
fuchsia_debug_symbols.bzl%_maybe_strip_elf() requires.
The error message looks like:

```
ERROR: /work/fx-bazel-sdk/build/bazel_sdk/tests/fuchsia/drivers/BUILD.bazel:20:19: in driver_binary_test rule //fuchsia/drivers:test_fuchsia_cc_driver_without_srcs:
Traceback (most recent call last):
        File "/work/fx-bazel-sdk/build/bazel_sdk/tests/fuchsia/drivers/driver_binary_test.bzl", line 18, column 54, in _driver_binary_test_impl
                stripped_resources, _debug_info = strip_resources(ctx, [resource])
        File "/usr/local/google/home/digit/.cache/bazel/_bazel_digit/775dc9a269db1b4b3ea101ce13a5b526/external/fuchsia_sdk/fuchsia/private/fuchsia_debug_symbols.bzl", line 78, column 53, in strip_resources
                stripped_resources.append(_maybe_process_elf(ctx, r, ids_txt))
        File "/usr/local/google/home/digit/.cache/bazel/_bazel_digit/775dc9a269db1b4b3ea101ce13a5b526/external/fuchsia_sdk/fuchsia/private/fuchsia_debug_symbols.bzl", line 99, column 37, in _maybe_process_elf
                cc_toolchain = find_cc_toolchain(ctx)
        File "/usr/local/google/home/digit/.cache/bazel/_bazel_digit/775dc9a269db1b4b3ea101ce13a5b526/external/rules_cc/cc/find_cc_toolchain.bzl", line 72, column 17, in find_cc_toolchain
                fail("In order to use find_cc_toolchain, your rule has to depend on C++ toolchain. See find_cc_toolchain.bzl docs for details.")
Error in fail: In order to use find_cc_toolchain, your rule has to depend on C++ toolchain. See find_cc_toolchain.bzl docs for details.
```

This will be addressed in a separate CL.

None of these changes should impact //build/bazel_sdk/scripts/bazel_test.py`
which still works as expected.

Original-Bug: 342332819
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1053435
Original-Revision: 8caea387da184f23a2e10311235101096603ab6d
GitOrigin-RevId: 9591b3612e6404105fcbfa7b0f482ca5bf97ce02
Change-Id: If04a583626cae063088dfcb322640c7b540c1c42