[roll] Roll fuchsia [proc][uapi] remove --size_t-is-usize
Needed because of bindgen update to fix:

error: unexpected argument '--size_t-is-usize' found

(Similar to https://fxrev.dev/813826, but for uapi instead
of magma.)

Test: ran bindgen.py, observed minimal changes in output
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/815471
Original-Revision: 49efb05009b27868405130decedb61f124a6b4b7
GitOrigin-RevId: 32babc874f7fb7096e13d12834e188d679b10f14
Change-Id: I630a750569e8e0dd2b1db0b450b46420b9e83009