[roll] Roll fuchsia [build] Suppress -Wunused-but-set-variable in brcmfmac
This patch suppresses -Wunused-but-set-variable warnings
that broadcom/brcmfmac code does not comply with.
The code that causes the issues is as the following:
error: variable 'mpnum' set but not used
error: variable 'nmp' set but not used
error: variable 'nsp' set but not used
error: variable 'iface_role_name' set but not used
error: variable 'cfg' set but not used

Original-Bug: 77973
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550047
Original-Revision: 2e220c0d95c28aa7fa8504aea871509ee92f9ec9
GitOrigin-RevId: 1eb27d3d2d586b9908a9054a124255ce233d278b
Change-Id: Ie231be19701f814dbfbe17bb4b82d280b675440e