[roll] Roll third_party/pigweed pw_console: Missing default_factory for dataclasses
Fixes the Python 3.11 error:
ValueError: mutable default <class 'collections.deque'> for field
history is not allowed: use default_factory.

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/135481
Original-Revision: 7e67d0fb4d1e033240f1b2559fa5a71b589be42e
GitOrigin-RevId: a697f516cdf93f0c4ef4d0b5656725aa060f971a
Change-Id: I3748605b31d84efcd7e4b3c6d8290dc7ed777728