[roll] Roll external/github.com/catapult-project/catapult Revert "Do not use iteritems"
This reverts commit 7a3a7363a7c321684eb327d1b8aa536986a12ff8.

Reason for revert: The usage of the package six has caused failures on bot https://ci.chromium.org/p/chrome/builders/ci/orderfile-clankium since 2020-03-10 for missing six:

File "/b/swarming/w/ir/cache/builder/src/third_party/catapult/devil/devil/devil_env.py", line 20, in <module>
    import six
ImportError: No module named six

TBR=jbudorick@chromium.org

Original change's description:
> Do not use iteritems
>
> Use six.iteritems() instead
> Also fix a type error when write str to tmpfile in py3,
> as default mode will be 'wb'
>
> Original-Bug: chromium:1185409
> Original-Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2739660

Original-Bug: chromium:1185409
Original-Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2786740
Original-Revision: 7c0bc6acf8793293e5ac3a5e4c6693af4dc8b51a
GitOrigin-RevId: 223d35034670065495323de5bdd99ce69fbe1741
Change-Id: Iab081f9937db8ac0ca384a7f7fd898a33d8fb4ec