[roll] Roll fuchsia [fidl][python] Don't panic on unsupported struct types (but still don't support them)
While compiling a struct, it's possible fidlgen_python may encounter
types or attributes Python bindings don't support. Instead of panicking
while compiling, bindings will still be compiled. The structs with
unsupported aspects will compile to a type that can't be constructed.
This allows compiling FIDL libraries which may contain some types that
aren't supported but don't need to be used.

An example runtime error looks like this

```
NotImplementedError: test.constants/Struct not supported.

    - int64_with_default annotated with allow_deprecated_struct_defaults
    - string_with_default annotated with allow_deprecated_struct_defaults
    - bool_with_default annotated with allow_deprecated_struct_defaults
    - enum_with_default annotated with allow_deprecated_struct_defaults
    - bits_with_default annotated with allow_deprecated_struct_defaults
```

Test: Verify plumbing works when compiling an unsupported attribute.
Original-Bug: 355717613, 404845645
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1231924
Original-Revision: c9ef546a150618576c5603abed3c46f90383d526
GitOrigin-RevId: d1dac30816d33772347dfc0aaa14f34d8b9d617b
Change-Id: I157d86eaa4ee990af44fe0b157b39ddb02c39d6a