[roll] Roll fuchsia [unification] Move //zircon/system/ulib/zircon-crypto to the GN build
Affected libraries:
//zircon/system/ulib/zircon-crypto

scripts/unification/verify_element_move.py --reference local/initial.json:

Error     aux         element removed: lib/ubsan/libzircon-crypto.so
Error     aux         element removed: lib/profile/libzircon-crypto.so
Error     aux         element removed: lib/ubsan-sancov-full/libzircon-crypto.so
Error     aux         element removed: lib/asan-ubsan/libzircon-crypto.so
Error     aux         element removed: lib/ubsan-sancov/libzircon-crypto.so
Error     aux         element removed: lib/asan/libzircon-crypto.so
Error     aux         element removed: lib/sancov/libzircon-crypto.so
Warning   aux         size change for lib/libzircon-crypto.so: +1% (149.7K)
Warning   image       size change for lib/libzircon-crypto.so: +1% (149.7K)
Error     image       size change for driver/zxcrypt.so: +128% (213.9K)
Error     image       shared library removed from driver/zxcrypt.so: libssl.so
Error     image       shared library removed from driver/zxcrypt.so: libcrypto.so
Warning   tests       size change for lib/libzircon-crypto.so: +1% (149.7K)
Error: summaries do not match!

Generated with //scripts/unification/move_cpp_library.py

Original-Bug: 36548
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/379196
GitOrigin-RevId: 6f7d712be029659b6a11ae36fe6d0c92eb3180bf
Change-Id: Iacd902727a12007208acf5eb3119fb627bc411a4