[roll] Roll fuchsia [session] make element_launcher errors less chatty
The current error-handling strategy is to panic. But
that creates a lot of chatter in the logs, due to the
backtrace.

This CL reduces the chatter, by logging the error, instead
of panic()-ing.

Before
------
[element_launcher] ERROR: [src/lib/diagnostics/log/rust/src/lib.rs(55)] PANIC info=panicked at ../../src/session/bin/element_launcher/src/main.rs:30:10:
Failed to propose element.: NotFound
[element_launcher] WARN: thread 'main' panicked at ../../src/session/bin/element_launcher/src/main.rs:30:10:
[element_launcher] WARN: Failed to propose element.: NotFound
[element_launcher] WARN: stack backtrace:
[element_launcher] WARN:   #0 std::sys_common::backtrace::_print_fmt(…) • ../../prebuilt/third_party/rust/linux-x64/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:135
[element_launcher] WARN:   #1 std::sys_common::backtrace::_print::«impl»::fmt(…) • ../../prebuilt/third_party/rust/linux-x64/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:44
...
[element_launcher] WARN:   #30…48 «Rust startup»

After
-----
[element_launcher] ERROR: [src/session/bin/element_launcher/src/main.rs(37)] failed to propose element

Caused by:
    manager error: NotFound

Test: manually forced the failure of launching, and found
Test: that element_launcher no longer generates a backtrace
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1071979
Original-Revision: 5925863c34ea465934dcaf133746ad563603fda1
GitOrigin-RevId: 1fbd051f810bf0ccfa6dca5797505c58b6f883f2
Change-Id: I4de94ad801de76cf215d2a8c43c6af9330e1e490