[roll] Roll fuchsia [superproject] Roll llvm-project/libc Revert D137868 "[libc] Fix builtin definition for memory functions"
This reverts commit da5d00ad0cf4d45e38287280c670b08e84e27411.

This caused -Wmacro-redefined
```
.../libc/src/string/memory_utils/op_x86.h:31:9: error: '_mm512_cmpneq_epi8_mask' macro redefined [-Werror,-Wmacro-redefined]
        ^
.../lib/clang/google3-trunk/include/avx512bwintrin.h:294:9: note: previous definition is here
        ^
```

GitOrigin-RevId: e21dea19a7179cd8b993dcf5fbcf5300a9106d94
Original-Revision: e71ff2bc22286e5e9111a925a5a8d0f83b63f7e2
Roller-URL: https://ci.chromium.org/b/8797290769089832961
CQ-Do-Not-Cancel-Tryjobs: true
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/761495
Original-Revision: 1e4a94744b18fca6a2a3f746ce222bb9bc755459
Change-Id: Iddc1f7737d581711781d036edc5622a1d777ce0e