[roll] Roll fuchsia [build][gidl] Generate empty test sources in subdirectories
This CL makes GIDL generate the sources for its empty tests in
subdirectories. These tests ensure that a program generated from an
empty .gidl file compiles, e.g. doesn't complain about unused imports.
However they were generated directly in $target_gen_dir which has been
causing this build error for me intermittently:

    Traceback (most recent call last):
      File "../../build/go/gen_library_metadata.py", line 122, in <module>
        sys.exit(main())
      File "../../build/go/gen_library_metadata.py", line 110, in main
        raise ValueError(
    ValueError: go_library requires that all Go files in source_dir be listed as sources, but the following files are missing from sources for target empty_gidl_tests: go_golden.go

The go_golden.go file is from the golden tests, which are unrelated but
also generated in $target_gen_dir.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/748883
Original-Revision: f1a21f1c23f9678d7adb854476f6a2d88e7ecd33
GitOrigin-RevId: e187ae6765262cf35eec9ddc2f7d649ffd217c9a
Change-Id: I292a0742cfdc140ddfaf7563cae52097cc956606