[roll] Roll third_party/openthread [build] Suppress Wunused-but-set-var in openthread
This patch suppresses -Wunused-but-set-variable warning in
openthread third party code that does not comply with.

The code that causes the issues are as the following:
1)../../third_party/openthread/src/cli/cli.cpp:1813:18: error: variable
  'i' set but not used
2)../../third_party/openthread/third_party/mbedtls/repo/library/bignum.c:1547:29:
   error: variable 't' set but not used
3)../../third_party/openthread/src/core/thread/mle_router.cpp:2051:30:
   error: variable 'storedCount' set but not used

Original-Bug: 96410
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/third_party/openthread/+/662984
Original-Revision: 773024bc3500fa368be7368a965c467cf7af7c2d
GitOrigin-RevId: 62e9d20b7b3de7b3b371bd66dd46a4f9a3bed9a8
Change-Id: I27a6baaf573e8e3b9b24b4ed49c7902aaa44b33c