[roll] Roll fuchsia [revert][check-licenses] Add new golden patterns for notice changes
This reverts commit b9e917178a09a2d34d0162fe1ab0613205403e70.

Reason for revert: This seems to be causing failures on some try runs with the output:

=== RUN   TestPatternsMatchExamples
LENGTH 97    golden_test.go:69: TestPatternsMatchExamples, got open host_x64/gen/tools/check-licenses/golden/examples/notice/bsd/fuchsia_bsd2.txt: no such file or directory
    golden_test.go:80: TestPatternsMatchExamples, host_x64/gen/tools/check-licenses/golden/patterns/notice/bsd/fuchsia_bsd2.lic pattern doesn't match example
--- FAIL: TestPatternsMatchExamples (0.12s)
FAIL

Original change's description:
> [check-licenses] Add new golden patterns for notice changes
>
> This adds new golden patterns and examples for updates to the Fuchsia
> standard notice header.
>
> Original-Bug: 66908
> Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/464989

TBR=jamesr@google.com,jcecil@google.com,omerlevran@google.com,auto-submit@fuchsia-infra.iam.gserviceaccount.com

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Original-Bug: 66908
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/465176
Original-Revision: fa450cd574bbcd4318016270a335b95c8ad8f6e6
GitOrigin-RevId: f8798c5a9bca4646ef2a18f01c829f7e56c227af
Change-Id: I8fea4cca7374b19f1f45a34813a656142f76c720