[roll] Roll fuchsia [build] Suppress -Wunused-but-set-par/var in dash
This patch suppresses -Wunused-but-set-parameter and
-Wunused-but-set-variable warnings in dash third party
code that does not comply with.

The code that causes the issues is as the following:
1) zircon/third_party/uapp/dash/src/eval.c:557:29: error: parameter
'flags' set but not used
2) zircon/third_party/uapp/dash/src/bltin/zircon.c:187:9: error:
variable 'count' set but not used

Original-Bug: 77973
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/550736
Original-Revision: 2c234950950e09926ab9ce230496143f1869149b
GitOrigin-RevId: 6152b849e03313e5c284b5804246383e8e76b4eb
Change-Id: I22ed8009d50c5f6a295f45a15693803c93536737