[roll] Roll fuchsia [build] Suppress -Wunused-but-set-var in simple-pt
This patch suppresses -Wunused-but-set-variable warning in
simple-pt third-party code that does not comply with.

The code that causes the issues is as the following:
error: variable 'n' set but not used

Original-Bug: 77973
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/551892
Original-Revision: 1139bc4ba60e8e38bee1d5c4419c9b90810b54f7
GitOrigin-RevId: 34a40d4cdab9fe6f4e6c4b2c711a022555b5c61d
Change-Id: I29940d7df1f191b6fee0df3a153ba4300317cfd4