[roll] Roll chromium/deps/icu@default Fix asm_to_inline_asm.py for Python 3
This fixes the following error:

FAILED: gen/third_party/icu/icudtl_dat.cc
.../depot_tools/bootstrap-2@3_8_10_chromium_23_bin/python3/bin/python3.exe ../../../v8/third_party/icu/scripts/asm_to_inline_asm.py gen/third_party/icu/icudtl_dat.S gen/th
ird_party/icu/icudtl_dat.cc
Traceback (most recent call last):
  File "../../../v8/third_party/icu/scripts/asm_to_inline_asm.py", line 31, in <module>
    sys.exit(asm_to_inl_asm(args.input, args.output))
  File "../../../v8/third_party/icu/scripts/asm_to_inline_asm.py", line 18, in asm_to_inl_asm
    outfile.write('__asm__(\n')
TypeError: a bytes-like object is required, not 'str'
[208/1882] ACTION //:run_torque(//build/toolchain/win:x64)
ninja: build stopped: subcommand failed.
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromium/deps/icu/+/3910618
Original-Revision: c67c0e6e2f118071ebfb313e34e06a7e64784abd
GitOrigin-RevId: 818feb653322d99b93a7db0739d5a1e92dceb52f
Change-Id: I3cdd724cf27cb8e65f453e65daab5eda183a0627