[roll] Roll fuchsia [fx set] Fix tests
The `fx set` tests had been passing, but producing some error logs that
suggested something was failing, e.g.:

  ERROR: Build directory missing or removed. (/tmp/tmp.foo)
  ERROR: run "fx set", or specify a build dir with --dir or "fx use"

This was happening because `fx set` runs `fx-change-build-dir` after it
runs `gn gen`, and `fx-change-build-dir` expects to be passed a valid
build directory containing an `fx.config` file with some environment
variables. That file is normally generated by GN itself, but in the
tests GN is mocked out, so `fx.config` isn't present in the build
directory after running `gn gen`.

That caused `fx set` to fail in the tests, but the tests themselves
weren't failing because they didn't make assertions about the exit code
of `fx set`. They only checked that `fx set` passed the expected args to
GN, so a failure in any `fx set` step after `gn gen` would not cause the
tests to fail.

So this was a two-part fix:
1. Have the mocked-out GN executable create a `fx.config` file in the
   build directory to make `fx-change-build-dir` happy so `fx set`
   passes.
2. Wrap every `fx set` invocation in the tests in `BT_ASSERT`, so in the
   future a test will fail if `fx set` produces a non-zero exit code. I
   tested this without the fix from #1 to confirm that it does indeed
   propagate the failure.

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/509818
Original-Revision: 4c7b6e8848ff9e7097b858a8f92778b22b064d5e
GitOrigin-RevId: 90a2373da311a01303597127140cd5f0edc4e099
Change-Id: I465c66b85ba251bf4ec0485a61d43b08ca251768