[roll] Roll fuchsia [fxfs] Add static assertion for versioned_type! with version too large.
This generates `static_assertions::const_assert!()` from the
versioned_type macro to check that the supplied version mapping
doesn't exceed LATEST_VERSION.

It should be trivial to extend this to check the lowest supported
version once we have code for that landed.

The errors are a bit unfortunate, but static_assertions doesn't support user-supplied error messages...
```
error[E0080]: evaluation of constant value failed  --> ../../src/storage/fxfs/src/serialized_types/types.rs:48:1
48 | / versioned_type! {
49 | |     19.. => StoreInfo,
50 | |     17.. => StoreInfo,
51 | |     8.. => StoreInfoV1,
52 | | }
   | |_^ attempt to compute `0_usize - 1_usize`, which would overflow
```

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/679329
Original-Revision: 4ff1f2a00f0d4d6fba7e0ccfcf91ce4466501b98
GitOrigin-RevId: 393c204c7cf57077e2a6edcb56e72ec4371bf388
Change-Id: Ie7e46f41b4cb88116ed72a86aa98ec9dd86dd847