[roll] Roll fuchsia [kernel][kcounter] Assert that kcounters are not defined in headers
Defining a kcounter in a header can lead to "split counters".  Add
a static assert to the KCOUNTER_DECLARE macro to prevent them from
being defined in a header.

Here's what the compiler error looks like if you try to define one in
handle.h:

```
In file included from ../../zircon/kernel/object/include/object/message_packet.h:18:
../../zircon/kernel/object/include/object/handle.h:236:1: error: static_assert failed due to requirement '2 == 0' "kcounters should not be defined in a header as doing so may result in the creation of multiple unrelated counters with the same name"
KCOUNTER(bad_counter, "bad")
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/453776
Original-Revision: 350d02916024b0d0a8bd389d71e3cde3a335c39c
GitOrigin-RevId: ca2f06dd6eebf8656aef9a166c5a8bb3c525c308
Change-Id: Ia62a3b671904f96e849eff4eeebbe44ac2558361