[roll] Roll cobalt Add a deinit command to cobaltb.py to remove the submodules from the repository.
This can be used in the fuchsia tree after running "./cobaltb.py setup" to
remove the submodules, allowing the normal jiri updates to work again.
Without this, jiri updates fail with:

$ jiri update
[13:41:31.873] Updating all projects
ERROR: while updating: Error while processing path "/usr/local/google/home/camrdale/fuchsia/third_party/cobalt/third_party/abseil-cpp": project.go:1589: stat /usr/local/google/home/camrdale/fuchsia/third_party/cobalt/third_party/abseil-cpp/.git/jiri: not a directory (and 18 other errors not shown here), while writing history: Error while processing path "/usr/local/google/home/camrdale/fuchsia/third_party/cobalt/third_party/abseil-cpp": project.go:1589: stat /usr/local/google/home/camrdale/fuchsia/third_party/cobalt/third_party/abseil-cpp/.git/jiri: not a directory (and 18 other errors not shown here)

Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/cobalt/+/398158
Original-Revision: 783133ba3139032ca4cc6df9681578e369ef14ae
GitOrigin-RevId: f5d768e9966f3a63658ee41026d7cdf84c67aa3d
Change-Id: I2dc4f8588b7ab541a8137e55bfd783a9687af91e