[roll] Roll third_party/mesa [build] Suppress -Wunused-but-set-variable in mesa
This patch suppresses -Wunused-but-set-variable warning in
mesa third party code that does not comply with.

The code that causes the issues are as the following:
1)../../third_party/mesa/src/intel/compiler/brw_fs_cmod_propagation.cpp:226:8:
  error: variable 'ip' set but not used
2)../../third_party/mesa/src/intel/compiler/brw_schedule_instructions.cpp:1711:8:
  error: variable 'instructions_to_schedule' set but not used

Original-Bug: 96410
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/third_party/mesa/+/663042
Original-Revision: 0a0abde6a1128d43430a8b4ff8b71590fe4db654
GitOrigin-RevId: 8eba40dbdefbcf3066efbf8c988cc6728608b6a5
Change-Id: I8498eab0c247d58d6e52ad75cadad1292e852382