[roll] Roll fuchsia [icu] Fix dependency management of third party ICU flavored rust crates
The old gni templates had a bug where different ICU flavors of some rust
crates would end up stored in the same `${target_output_dir}`.  That
would cause that output dir to be included in `-Ldependency=...`
argslist for `rustc` invocation. This would in turn cause rustc to
consider all ICU flavors of each ICU-specific crate when linking,
instead of only one flavor. And if it so happens that among those ICU
flavors some have different hashes, we get an error:

```
error: found crates (`rust_icu_common` and `rust_icu_common`) with colliding StableCrateId values.
```

There was another issue that together with the above caused the bug. The
output directory for unflavored crates was passed into
`-Ldependency=...`, affecting the crate resolution, and allowing
compiler access to multiple ICU flavors of the same crate in a single
compilation.

This is only an issue in `//third_party/rust_crates` as it is normally
the only place where different flavors of crates coexist, and where this
bug could manifest itself.

The new code ensures that different ICU flavors get emitted into a
separate directory. With this change, a `rustc` invocation will
henceforth never have access to more than one ICU flavor for each crate
it needs as a dependency.

Original-Bug: b/330351469
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1011499
Original-Revision: 684c808be626691dfde6c7d761c9754b7cc91336
GitOrigin-RevId: e6e85177d49679f0490625eef5a708257a991f6b
Change-Id: I7b43474fd738424538f2295356344a42203e8068