[roll] Roll third_party/acpica [build] Suppress -Wunused-but-set-var in acpica
This patch suppresses -Wunused-but-set-variable warning in
acpica third party code that does not comply with.

The code that causes the issue is as the following:
1) third_party/acpica/source/components/namespace/nsaccess.c:341:29:
   error: variable 'NumCarats' set but not used
2) third_party/acpica/source/common/dmtbdump.c:82:29:
   error: parameter 'AbsoluteOffset' set but not used

Original-Bug: 96410
Original-Revision: ba7b6a7570259b4743c234014a8b8befe57b19b0
GitOrigin-RevId: b8a82881009505a11398b230e7c2e69c3df3aa45
Change-Id: Ib04e851f5fac6ef80dcf416916575c4e547be55d