[roll] Roll fuchsia [bazel] bazel_action.py: Add @rules_python_internal to the list of ignored repositories
This is necessary to roll rules_python-0.36 with tqr/915970.
Without this change, the build will fail with an error that looks
like:

```
ERROR: Found ignored external repository files:
  @@rules_python_internal//:py_internal.bzl
  @@rules_python_internal//:rules_python_config.bzl

These files are likely generated by a Bazel repository rule which has
no associated content hash file. Due to this, Bazel may regenerate them
semi-randomly in ways that confuse Ninja dependency computations.
```

In the future, we may have significantly more ignorable repositories
like this one, and their list will probably not be hard-coded in the
script, but determined by the workspace setup script. For now, this
small CL will do.

Original-Bug: 381934267
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1169054
Original-Revision: 86d7c83ff45c544d004b16bf249cf46235e322f5
GitOrigin-RevId: 1e47058c05028d2282093e6664c1e6ae572bf022
Change-Id: I5dd1329948366df5ef92922ea1a865f11a4839f1