[roll] Roll fuchsia Revert "[clidoc] Using JSON info from ffx to generate docs"
This reverts commit a77b2a2fb8dc8a3f050c9cf5504f4d6e490be3e0.

Reason for revert: broke `fx build`:

```
λ fx build
ninja: Entering directory `/REDACTED/development/fuchsia/out/core_release'
[21/1198](8) ACTION //tools/docsgen:invoke_clidoc(//build/toolchain/fuchsia:x64)
FAILED: obj/tools/docsgen/clidoc_out.tar.gz
../../prebuilt/third_party/python3/linux-x64/bin/python3 -S ../../build/rbe/output_leak_scanner.py --label //tools/docsgen:invoke_clidoc\(//build/toolchain/fuchsia:x64\) obj/tools/docsgen/clidoc_out.tar.gz -- ../../build/gn_run_binary.sh ../../prebuilt/third_party/clang/linux-x64/bin host_x64/clidoc -o gen/tools/docsgen/sdk-docs --quiet --archive-path obj/tools/docsgen/clidoc_out.tar.gz --depfile obj/tools/docsgen/invoke_clidoc.d --sdk-root . --sdk-manifest host_x64/sdk/manifest/host_tools.internal
Error: Unable to write generate doc for "/REDACTED/fuchsia/out/core_release/host_x64/ffx" to "gen/tools/docsgen/sdk-docs"

Caused by:
    "/REDACTED/fuchsia/out/core_release/host_x64/ffx" failed exit status: 1: BUG: An internal command error occurred.
    Error: json parsing:Usage: ffx-component [-c <config...>] [-e <env>] [--machine <machine>] [--stamp <stamp>] [-t <target>] [-T <timeout>] [-l <log-level>] [--isolate-dir <isolate-dir>] [-v] [subcommand...]

    Fuchsia's developer tool

    Options:
      -c, --config      override configuration values (key=value or json)
      -e, --env         override the path to the environment configuration file
                        (file path)
      --machine         produce output for a machine in the specified format;
                        available formats: "json", "json-pretty"
      --stamp           create a stamp file at the given path containing the exit
                        code
      -t, --target      apply operations across single or multiple targets
      -T, --timeout     override default proxy timeout
      -l, --log-level   sets the log level for ffx output (default = Info). Other
                        possible values are Info, Error, Warn, and Trace. Can be
                        persisted via log.level config setting.
      --isolate-dir     turn on isolation mode using the given directory to isolate
                        all config and socket files into the specified directory.
                        This overrides the FFX_ISOLATE_DIR env variable, which can
                        also put ffx into this mode.
      -v, --verbose     logs ffx output to stdio according to log level
      --help            display usage information

    Built-in Commands:

      component         Discover and manage components
      metadata          Print out this subtool's FHO metadata json

    Note: There may be more commands available, use `ffx-component commands` for a complete list.
    See 'ffx-component <command> help' for more information on a specific command.

        1.  expected value at line 1 column 1
    More information may be available in ffx host logs in directory:
        /REDACTED/.local/share/Fuchsia/ffx/cache/logs
```

Original change's description:
> [clidoc] Using JSON info from ffx to generate docs
>
> This uses the `--machine json --help` output of ffx to access
> the JSON encoded information for the command line. This allows
> generating a complete help document for all subcommands.
>
> Staged at: https://fuchsia.devsite.corp.google.com/reference/tools/sdk/ffx
>
> Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/965624

No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/966119
Original-Revision: 1c63f6183e9e32f5881894d92d9b433df28f02af
GitOrigin-RevId: 435beaf117964bc90e841b30f5f84207dd1a739e
Change-Id: Iee8c19762374d646760f06250457b772cf495c14