[roll] Roll third_party/openssh-portable [build] Suppress -Wunused-but-set-variable in openssh-portable
This patch suppresses -Wunused-but-set-variable warning in
openssh-portable third party code that does not comply with.

The code that causes the issue is as the following:
third_party/openssh-portable/kex.c:1172:14: error: variable 'i' set but
not used

Original-Bug: 96410
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/third_party/openssh-portable/+/663831
Original-Revision: bb9035e48e78e06498e4bf1471e1365b2c95269a
GitOrigin-RevId: dbf48db02b77cfc775ea7a44f70f6bba25fc0802
Change-Id: I30188a6bca01bcc0b9fbdf42e0fa1740b4e78d5a