[roll] Roll external/github.com/catapult-project/catapult Revert "Do not use StringIO"
This reverts commit 1b1b89d649f1cd031fd266be3744e071403a2965.

Reason for revert: Causing the catapult roll to fail: https://ci.chromium.org/ui/p/chromium/builders/try/android-binary-size/750590/overview

  File "/b/s/w/ir/cache/builder/src/third_party/catapult/devil/devil/utils/cmd_helper.py", line 18, in <module>
  import six
  ImportError: No module named six

Original change's description:
> Do not use StringIO
>
> In attempt to make catapult work under py3.
>
> Original-Bug: chromium:1183514
> Original-Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2726534

Original-Bug: chromium:1183514
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Original-Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/2739458
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Original-Revision: a2e61d839066063bbd5682f25c179f156827de71
GitOrigin-RevId: 83295f5deb9be360d1e732671e82053150af9689
Change-Id: I19a9f65693215834d1e4b75d430a3f9c45942e98