[roll] Roll fuchsia [starnix] Update generate.py and remove __bindgen_padding_0
This CL 1) updates the outputs of generate.py so that they match what the script does at ToT (outputs such as arm.rs at ToT haven't been updated/synced), and 2) makes sure fx build works after the update.

Steps:
1. Run `./src/starnix/lib/linux_uapi/generate.py` (no edits)
This results in some changes, notably, io_uring_sqe__bindgen_ty_6 updating to a struct and having 5 params.

2. Run `fx build`. This fails due to:
```
error[E0080]: evaluation of `std::mem::size_of::<io_uring_sqe>` failed
 --> /b/s/w/ir/x/w/fuchsia-third_party-rust/library/core/src/mem/mod.rs:1229:26
  |
  = note: values of the type `[u8; 18446744073709551608]` are too big for the target architecture
```
This is https://github.com/rust-lang/rust-bindgen/issues/3068.

3. Patch in the generate.py edit. Run `./src/starnix/lib/linux_uapi/generate.py` (with edit). Note that generated files now do not have the `pub __bindgen_padding_0` line.

4. `fx build` completes.

Once's qsr's fix at https://github.com/rust-lang/rust-bindgen/pull/3173 is merged and rolled in, we shouldn't need to do the regex replace.

Original-Bug: 398914504
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/1235157
Original-Revision: 3b130710ba6aac0d9130bc718184bfaf34abbfa8
GitOrigin-RevId: c1e0371e35ebae79d27ecaaac3fc16ae30461a38
Change-Id: I4169f94aa0c01a8be2ddcddb6b094e46b6c7108d