[roll] Roll fuchsia [http-client] Assert error is None
Currently we are seeing a very anemic test failure:
```
[stdout - test_fetch_http_big_stream]:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(200)`',
../../src/connectivity/network/http-client/integration/src/lib.rs:90:5
```

This change should provide more information when such failures occur.

Replace point accesses with destructuring while I'm here.

Multiply: http-client-integration-test
Original-Bug: 82499
Original-Reviewed-on: https://fuchsia-review.googlesource.com/c/fuchsia/+/571081
Original-Revision: de0049e40a4eef28b368058f4c1c0864344830ca
GitOrigin-RevId: b60039e984c9e996ff3895e8e22e923038d9f3b8
Change-Id: I5767e8d119d9c0b88c991a3b121c831f315d36a6